package com.cqhhxk.paddleocr.ppocrlabel;

import com.cqhhxk.utils.FileUtils;
import com.cqhhxk.utils.StringUtils;
import jakarta.validation.constraints.NotNull;

/**
 * PPOCRLabel Transformer CmdLine Processor
 * @author george
 */
public class TransformerCmdLineProcessor {

    public static void main(String[] args) {
        TransformerArgs transformerArgs = parseArgs(args);

        if (validateTransformerArgs(transformerArgs)) {
            doTransform(transformerArgs);
        } else {
            printUsage();
        }
    }

    /**
     * Parse command line arguments
     * @param args Arguments
     * @return TransformerArgs
     */
    private static @NotNull TransformerArgs parseArgs(@NotNull String[] args) {
        TransformerArgs transformerArgs = new TransformerArgs();
        for (int i = 0; i < args.length - 1; i++) {
            if ("--image-dir".equals(args[i])) {
                transformerArgs.setCroppedImageDir(args[i+1]);
            } else if ("--label-file".equals(args[i])) {
                transformerArgs.setLabelFile(args[i+1]);
            }
        }
        return transformerArgs;
    }

    /**
     * Check if a TransformerArgs variable valid
     * @param args TransformerArgs
     * @return True if valid, or false if invalid
     */
    private static boolean validateTransformerArgs(@NotNull TransformerArgs args) {
        return !StringUtils.isBlank(args.getCroppedImageDir()) && !StringUtils.isBlank(args.getLabelFile());
    }

    /**
     * Do transformation
     * @param args TransformerArgs
     */
    private static void doTransform(TransformerArgs args) {
        new Transformer(args).transform();
    }

    /**
     * Print the usage of this program
     */
    private static void printUsage() {
        String path = TransformerCmdLineProcessor.class.getProtectionDomain().getCodeSource().getLocation().getPath();
        String jarName = FileUtils.extractFilename(path, true);
        System.out.println("Utility to transform label file generated by PPOCRLabel to suite cropped images");
        System.out.println();
        System.out.println("Usage:");
        System.out.println("  java -jar " + jarName + " --image-dir <PPOCRLabel cropped image folder> --label-file <original PPOCRLabel label file>");
        System.out.println();
    }
}
